name: test_task_mobile
description: "A Flutter project to perform requests to the server."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
